"""
UUIDv7 Migration Tool — Detect UUIDv4 keys and generate zero-downtime migration.

UUIDv4 is random → index fragmentation, poor cache locality, slow inserts.
UUIDv7 is time-sorted → sequential inserts, better page splits, 30% faster INSERTs.

PostgreSQL 18 adds built-in uuidv7(). For PG14-17, use the pg_uuidv7 extension.

This module:
1. Scans all tables for UUID primary keys
2. Detects whether defaults use gen_random_uuid() (v4) vs uuidv7()
3. Estimates performance impact (index bloat, cache misses)
4. Generates per-table migration scripts (zero-downtime)
5. Provides batch migration orchestration

Usage:
    from querysense.uuid_migrator import UUIDMigrator, UUIDMigrationPlan

    migrator = UUIDMigrator()
    plan = await migrator.analyze(dsn)
    print(plan.format_text())
    script = plan.generate_migration_sql()
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class UUIDColumn:
    """A UUID column found in the database."""
    schema: str = "public"
    table: str = ""
    column: str = ""
    is_primary_key: bool = False
    column_default: str = ""
    uuid_version: str = "v4"  # v4, v7, unknown
    table_size_bytes: int = 0
    index_size_bytes: int = 0
    row_count: int = 0
    index_bloat_estimate_pct: float = 0.0
    fk_references: list[dict[str, str]] = field(default_factory=list)

    @property
    def table_size_mb(self) -> float:
        return self.table_size_bytes / (1024 * 1024)

    @property
    def index_size_mb(self) -> float:
        return self.index_size_bytes / (1024 * 1024)

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "table": self.table,
            "column": self.column,
            "is_primary_key": self.is_primary_key,
            "uuid_version": self.uuid_version,
            "table_size_mb": round(self.table_size_mb, 1),
            "index_size_mb": round(self.index_size_mb, 1),
            "row_count": self.row_count,
            "bloat_estimate_pct": round(self.index_bloat_estimate_pct, 1),
            "fk_references": len(self.fk_references),
        }


@dataclass
class UUIDMigrationPlan:
    """Complete UUID migration analysis."""
    pg_version: int = 0
    has_pg_uuidv7: bool = False
    has_native_uuidv7: bool = False
    columns: list[UUIDColumn] = field(default_factory=list)
    total_tables_affected: int = 0
    total_size_mb: float = 0.0
    total_index_size_mb: float = 0.0
    estimated_insert_improvement_pct: float = 30.0
    estimated_cache_improvement_pct: float = 15.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "pg_version": self.pg_version,
            "native_uuidv7": self.has_native_uuidv7,
            "pg_uuidv7_extension": self.has_pg_uuidv7,
            "tables_affected": self.total_tables_affected,
            "total_size_mb": round(self.total_size_mb, 1),
            "total_index_size_mb": round(self.total_index_size_mb, 1),
            "estimated_insert_improvement_pct": self.estimated_insert_improvement_pct,
            "columns": [c.to_dict() for c in self.columns],
        }

    def generate_migration_sql(self, batch_size: int = 10000) -> str:
        """Generate zero-downtime migration SQL for all UUID columns."""
        parts: list[str] = []

        parts.append("-- UUIDv7 Migration Script")
        parts.append("-- Generated by QuerySense")
        parts.append("-- Run each table migration in a separate transaction")
        parts.append("")

        if not self.has_native_uuidv7 and not self.has_pg_uuidv7:
            parts.append("-- Step 0: Install pg_uuidv7 extension (PG14-17)")
            parts.append("CREATE EXTENSION IF NOT EXISTS pg_uuidv7;")
            parts.append("")

        uuidv7_func = "uuidv7()" if self.has_native_uuidv7 else "uuid_generate_v7()"

        for col in self.columns:
            if col.uuid_version == "v7":
                continue
            if not col.is_primary_key:
                continue

            fqn = f'"{col.schema}"."{col.table}"'
            parts.append(f"-- Table: {fqn} ({col.table_size_mb:.1f} MB, {col.row_count:,} rows)")
            parts.append(f"-- Current bloat estimate: {col.index_bloat_estimate_pct:.1f}%")
            parts.append("")

            parts.append(f"-- Step 1: Change default for new inserts")
            parts.append(f'ALTER TABLE {fqn} ALTER COLUMN "{col.column}" SET DEFAULT {uuidv7_func};')
            parts.append("")

            if col.fk_references:
                parts.append(f"-- Note: {len(col.fk_references)} foreign key references:")
                for fk in col.fk_references:
                    parts.append(f"--   {fk['table']}.{fk['column']} REFERENCES {col.table}.{col.column}")
                parts.append("")

            parts.append(f"-- Step 2: Rebuild index CONCURRENTLY for better locality")
            parts.append(f"REINDEX INDEX CONCURRENTLY {fqn}_pkey;")
            parts.append("")

        return "\n".join(parts)

    def format_text(self) -> str:
        lines = [
            "",
            "  UUID PRIMARY KEY ANALYSIS",
            "  " + "=" * 55,
            f"  PostgreSQL: PG{self.pg_version}",
            f"  Native uuidv7(): {'YES' if self.has_native_uuidv7 else 'NO (use pg_uuidv7 extension)'}",
            f"  pg_uuidv7 extension: {'installed' if self.has_pg_uuidv7 else 'not found'}",
            "",
            f"  Tables with UUID primary keys: {self.total_tables_affected}",
            f"  Total table size: {self.total_size_mb:.1f} MB",
            f"  Total index size: {self.total_index_size_mb:.1f} MB",
            "",
        ]

        if self.columns:
            lines.append("  UUID COLUMNS:")
            lines.append(f"  {'Table':<30} {'Version':<6} {'Size(MB)':>9} {'Bloat%':>7} {'Rows':>12}")
            lines.append("  " + "-" * 70)
            for col in sorted(self.columns, key=lambda c: -c.table_size_bytes):
                if not col.is_primary_key:
                    continue
                lines.append(
                    f"  {col.schema + '.' + col.table:<30} {col.uuid_version:<6} "
                    f"{col.table_size_mb:>9.1f} {col.index_bloat_estimate_pct:>6.1f}% "
                    f"{col.row_count:>12,}"
                )
            lines.append("")

        v4_count = sum(1 for c in self.columns if c.uuid_version == "v4" and c.is_primary_key)
        if v4_count > 0:
            lines.append(f"  PERFORMANCE IMPACT (UUIDv4 → UUIDv7):")
            lines.append(f"  INSERT throughput: +{self.estimated_insert_improvement_pct:.0f}%")
            lines.append(f"  Cache hit ratio: +{self.estimated_cache_improvement_pct:.0f}%")
            lines.append(f"  Index fragmentation: Eliminated for new inserts")
            lines.append("")
            lines.append(f"  Run `querysense audit uuids --v7 --generate-sql` for migration script")

        lines.append("")
        return "\n".join(lines)


_UUID_COLUMNS_SQL = """
SELECT
    c.table_schema, c.table_name, c.column_name,
    c.column_default,
    tc.constraint_type,
    pg_relation_size(
        quote_ident(c.table_schema) || '.' || quote_ident(c.table_name)
    ) AS table_size,
    COALESCE((
        SELECT pg_relation_size(i.indexrelid)
        FROM pg_index i
        JOIN pg_class pc ON pc.oid = (
            quote_ident(c.table_schema) || '.' || quote_ident(c.table_name)
        )::regclass
        WHERE i.indrelid = pc.oid AND i.indisprimary
    ), 0) AS pk_index_size,
    COALESCE((
        SELECT n_live_tup FROM pg_stat_user_tables st
        WHERE st.schemaname = c.table_schema AND st.relname = c.table_name
    ), 0) AS row_count
FROM information_schema.columns c
LEFT JOIN information_schema.constraint_column_usage ccu
    ON c.table_schema = ccu.table_schema
    AND c.table_name = ccu.table_name
    AND c.column_name = ccu.column_name
LEFT JOIN information_schema.table_constraints tc
    ON ccu.constraint_name = tc.constraint_name
    AND tc.constraint_type = 'PRIMARY KEY'
WHERE c.data_type = 'uuid'
    AND c.table_schema NOT IN ('pg_catalog', 'information_schema')
ORDER BY table_size DESC
"""

_FK_REFERENCES_SQL = """
SELECT
    tc.table_schema, tc.table_name, kcu.column_name,
    ccu.table_schema AS ref_schema,
    ccu.table_name AS ref_table,
    ccu.column_name AS ref_column
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage ccu
    ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
    AND ccu.table_schema = $1
    AND ccu.table_name = $2
    AND ccu.column_name = $3
"""

_BLOAT_ESTIMATE_SQL = """
SELECT
    CASE WHEN bs * tpl_data_per_page > 0
    THEN 100.0 * (1.0 - (reltuples * (datahdr + 16)) / (relpages::float * bs))
    ELSE 0.0
    END AS bloat_pct
FROM (
    SELECT
        8192 AS bs,
        (SELECT n_live_tup FROM pg_stat_user_tables WHERE relname = $1) AS reltuples,
        pg_relation_size($1::regclass) / 8192 AS relpages,
        23 AS datahdr,
        8192 - 24 AS tpl_data_per_page
) sub
"""


class UUIDMigrator:
    """
    Scan database for UUID primary keys and generate v7 migration plan.
    """

    async def analyze(self, dsn: str) -> UUIDMigrationPlan:
        """Run complete UUID analysis."""
        try:
            import asyncpg
        except ImportError:
            raise RuntimeError("asyncpg required: pip install asyncpg")

        plan = UUIDMigrationPlan()
        conn = await asyncpg.connect(dsn)

        try:
            version = await conn.fetchval(
                "SELECT current_setting('server_version_num')::int"
            )
            plan.pg_version = version // 10000
            plan.has_native_uuidv7 = plan.pg_version >= 18

            try:
                ext = await conn.fetchval(
                    "SELECT 1 FROM pg_extension WHERE extname = 'pg_uuidv7'"
                )
                plan.has_pg_uuidv7 = ext is not None
            except Exception:
                pass

            await self._scan_uuid_columns(conn, plan)
            await self._check_fk_references(conn, plan)
            await self._estimate_bloat(conn, plan)

            pk_cols = [c for c in plan.columns if c.is_primary_key]
            plan.total_tables_affected = len(pk_cols)
            plan.total_size_mb = sum(c.table_size_mb for c in pk_cols)
            plan.total_index_size_mb = sum(c.index_size_mb for c in pk_cols)

        finally:
            await conn.close()

        return plan

    async def _scan_uuid_columns(self, conn: Any, plan: UUIDMigrationPlan) -> None:
        try:
            rows = await conn.fetch(_UUID_COLUMNS_SQL)
        except Exception:
            return

        for row in rows:
            default = row["column_default"] or ""
            uuid_version = self._detect_uuid_version(default)

            plan.columns.append(UUIDColumn(
                schema=row["table_schema"],
                table=row["table_name"],
                column=row["column_name"],
                is_primary_key=row["constraint_type"] == "PRIMARY KEY",
                column_default=default,
                uuid_version=uuid_version,
                table_size_bytes=row["table_size"] or 0,
                index_size_bytes=row["pk_index_size"] or 0,
                row_count=row["row_count"] or 0,
            ))

    def _detect_uuid_version(self, default_expr: str) -> str:
        lower = default_expr.lower()
        if "uuidv7" in lower or "uuid_generate_v7" in lower:
            return "v7"
        if "gen_random_uuid" in lower or "uuid_generate_v4" in lower:
            return "v4"
        if "uuid" in lower:
            return "v4"
        return "unknown"

    async def _check_fk_references(
        self, conn: Any, plan: UUIDMigrationPlan,
    ) -> None:
        for col in plan.columns:
            if not col.is_primary_key:
                continue
            try:
                refs = await conn.fetch(
                    _FK_REFERENCES_SQL, col.schema, col.table, col.column,
                )
                col.fk_references = [
                    {"table": r["table_name"], "column": r["column_name"]}
                    for r in refs
                ]
            except Exception:
                pass

    async def _estimate_bloat(
        self, conn: Any, plan: UUIDMigrationPlan,
    ) -> None:
        for col in plan.columns:
            if not col.is_primary_key or col.row_count == 0:
                continue
            try:
                bloat = await conn.fetchval(_BLOAT_ESTIMATE_SQL, col.table)
                col.index_bloat_estimate_pct = max(0.0, float(bloat or 0))
            except Exception:
                pass
